# 配置端口
server:
  port: 10101
spring:
  datasource:
    # 基础属性
    # 腾讯云 mysql 数据库连接
    url: jdbc:mysql://cdb-csnz8qhs.cd.tencentcdb.com:10087/exam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: code-fusheng
    # 可以不配置，根据url自动识别，建议配置
    driver-class-name: com.mysql.cj.jdbc.Driver
#以下为JWT的配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Zh-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico










